# Generated by Django 4.0.4 on 2022-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('participants', models.ManyToManyField(to='core.participant')),
            ],
            options={
                'db_table': 'Interview',
            },
        ),
    ]
